name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [ 14, 16, 18 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build
      - run: npm test
  integration-test:
    strategy:
      fail-fast: false
      matrix:
        working-directory: [ "cypress_9", "cypress_js", "cypress_ts" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: parse
        uses: ./   # Execute action using a fake Cypress test setup
        with:
          working-directory: __tests__/fixtures/${{ matrix.working-directory }}
      - run: |
          value="${{ fromJson(steps.parse.outputs.integration-tests)[0] }}"
          [ -z "${value}" ] && echo "::debug::No test found" && exit 1
          exit 0
